export const STREAM_OPTIONS = [
    "Science",
    "Commerce",
    "Arts/Humanities",
];

export const GENDER_OPTIONS = [
    "Male",
    "Female",
    "Other",
];

export const EDUCATION_LEVEL_OPTIONS = [
    { value: "8", label: "Class 8" },
    { value: "9", label: "Class 9" },
    { value: "10", label: "Class 10" },
    { value: "12", label: "Class 12" },
    { value: "Graduate", label: "Graduate" },
    { value: "Post-Graduate", label: "Post-Graduate" },
    { value: "Doctorate", label: "Doctorate/Ph.D." },
];

export const SUBJECT_OPTIONS = [
    "Physics",
    "Chemistry",
    "Mathematics",
    "Biology",
    "Botany",
    "Zoology",
    "English",
    "Hindi",
    "Sanskrit",
    "History",
    "Geography",
    "Political Science",
    "Economics",
    "Accountancy",
    "Business Studies",
    "Computer Science",
    "Physical Education",
    "Psychology",
    "Sociology",
    "Philosophy",
    "Fine Arts",
    "Home Science",
    "Legal Studies",
    "Entrepreneurship",
    "General Knowledge",
    "Environmental Science",
    "Information Technology",
    "Artificial Intelligence",
    "Data Science",
    "Engineering Graphics",
    "Agriculture",
    "Marketing",
    "Fashion Studies",
    "Music",
    "Dance",
    "Biotechnology",
    "Informatics Practices",
    "Applied Mathematics",
    "Statistics",
    "Business Mathematics",
    "Mass Media Studies",
    "Journalism",
    "Anthropology",
    "Public Administration",
    "Regional Languages",
    "Social Science",
    "Civics",
    "Work Experience",
    "Web Application Development",
    "IT/ITES",
    "Retail",
    "Tourism",
    "Beauty & Wellness",
    "Food Production",
    "Banking & Insurance",
    "Design Thinking & Innovation",
    "Financial Markets Management",
    "Yoga",
    "French",
    "German",
    "Spanish",
    "Marathi",
    "Gujarati",
    "Punjabi",
    "Kannada",
    "Malayalam",
    "Odia",
    "Assamese",
    "Urdu",
    "Art Education",
    "Health Education",
];
